name: Build Test

on:
  pull_request:
    branches:
      - 'main'

env:
  IMAGE: registry.indicareleve.me/2fsicurezza

jobs:
  docker:
    environment:
      name: Test
      url: https://test.2fsicurezza.it


    runs-on: ubuntu-latest
    steps:
    - name: Generate build ID
      id: prep
      run: echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV     

    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to private registry
      uses: docker/login-action@v2
      with:
        registry: https://registry.indicareleve.me
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push testing
      uses: docker/build-push-action@v3
      env:
        PUBLIC_HCAPTCHA_SITEKEY: ${{ secrets.PUBLIC_HCAPTCHA_SITEKEY }}
        PUBLIC_SITE_URL: ${{ secrets.PUBLIC_SITE_URL }}
        
        HCAPTCHA_SECRETKEY: ${{ secrets.HCAPTCHA_SECRETKEY }}

        MAILERSEND_APIKEY: ${{ secrets.MAILERSEND_APIKEY }}
        MAILERSEND_TEMPLATEID: ${{ secrets.MAILERSEND_TEMPLATEID }}
        MAILERSEND_TO: ${{ secrets.MAILERSEND_TO }}
        MAILERSEND_FROM: ${{ secrets.MAILERSEND_FROM }}
      with:
        push: true
        tags: |
              ${{ env.IMAGE }}:${{ env.BUILD_ID }}-testing-${{ github.event.pull_request.head.ref }}
              ${{ env.IMAGE }}:testing